// Generated by https://quicktype.io

import { IsNumber, IsObject, IsString } from "class-validator";

export class LoanDto {
    @IsString()
    accountHolderKey: string;
    @IsString()
    accountHolderType: string;
    @IsNumber()
    loanAmount: number;
    @IsString()
    productTypeKey: string;
    @IsObject()
    interestSettings: InterestSettings;
    @IsObject()
    scheduleSettings: ScheduleSettings;
    @IsObject()
    disbursementDetails: DisbursementDetails;
    @IsObject()
    _Informacion_Adicional: InformacionAdicional;
}

export interface InformacionAdicional {
    Codigo_Promotor: string;
}

export interface DisbursementDetails {
    expectedDisbursementDate: string;
    firstRepaymentDate: string;
}

export interface InterestSettings {
    interestRate: number;
}

export interface ScheduleSettings {
    gracePeriod: number;
    repaymentInstallments: number;
    repaymentPeriodCount: number;
    repaymentPeriodUnit: string;
    repaymentScheduleMethod: string;
    scheduleDueDatesMethod: string;
}
